name: 'Presubmit Checks'
description: 'GitHub Action for a suite of useful presubmit/premerge checks.'
author: 'Alexander Zlatin'

inputs:
  repo-token:
    description: A token that grants access to read/write actions. Usually secrets.GITHUB_TOKEN.
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - run: $GITHUB_ACTION_PATH/gradlew :presubmitchecks-cli:installDist
      shell: bash
    - run: $GITHUB_ACTION_PATH/presubmitchecks-cli/build/install/presubmitchecks-cli/bin/presubmitchecks-cli github-action
      shell: bash
      env:
        GITHUB_REPO_TOKEN: ${{ inputs.repo-token }}