name: 'Presubmit Checks'
description: 'GitHub Action for a suite of useful presubmit/premerge checks.'
author: 'Alexander Zlatin'

inputs:
  repo-token:
    description: A token that grants access to read/write actions. Usually secrets.GITHUB_TOKEN.
    required: true
  config-file:
    description: Path to the presubmit checks config file.
    required: false
  apply-fixes:
    description: Applies fixes automatically.
    required: false
    default: "false"
outputs:
  applied-fixes:
    description: "Set to 1 if fixes were applied"
    value: ${{ steps.presubmitchecks.outputs.APPLIED_FIXES }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Get Action SHA
      shell: bash
      run: |
        pushd ${{ github.action_path }}
          ACTION_SHA=$(git rev-parse HEAD)
          echo "ACTION_SHA=$ACTION_SHA" >> $GITHUB_ENV
          ACTION_PATH=$(pwd)
          echo "ACTION_PATH=$ACTION_PATH" >> $GITHUB_ENV
        popd
    - name: Restore Cache
      id: cache-cli-restore
      uses: actions/cache@v4
      with:
        path: ${{ env.ACTION_PATH }}/presubmitchecks-cli/build/install/presubmitchecks-cli
        key: ${{ runner.os }}-presubmitchecks-${{ env.ACTION_SHA }}
    - name: Install Presubmit CLI
      if: steps.cache-cli-restore.outputs.cache-hit != 'true'
      run: |
        pushd ${{ env.ACTION_PATH }}
          chmod +x ./gradlew
          ./gradlew :presubmitchecks-cli:installDist
        popd
      shell: bash

    - name: Run Presubmit Checks
      run: ${{ env.ACTION_PATH }}/presubmitchecks-cli/build/install/presubmitchecks-cli/bin/presubmitchecks-cli github-action
      shell: bash
      id: presubmitchecks
      env:
        GITHUB_REPO_TOKEN: ${{ inputs.repo-token }}
        INPUT_CONFIG_FILE: ${{ inputs.config-file }}
        INPUT_APPLY_FIXES: ${{ inputs.apply-fixes }}
