name: 'Presubmit Checks'
description: 'GitHub Action for a suite of useful presubmit/premerge checks.'
author: 'Alexander Zlatin'

inputs:
  repo-token:
    description: A token that grants access to read/write actions. Usually secrets.GITHUB_TOKEN.
    required: true
  config-file:
    description: Path to the presubmit checks config file.
    required: false
  apply-fixes:
    description: Applies fixes automatically.
    required: false
    default: "false"
outputs:
  applied-fixes:
    description: "Set to 1 if fixes were applied"
    value: ${{ steps.presubmitchecks.outputs.APPLIED_FIXES }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - run: |
        echo "::group::Install CLI"
        $GITHUB_ACTION_PATH/gradlew :presubmitchecks-cli:installDist
        echo "::endgroup::"
      shell: bash
    - run: $GITHUB_ACTION_PATH/presubmitchecks-cli/build/install/presubmitchecks-cli/bin/presubmitchecks-cli github-action
      shell: bash
      id: presubmitchecks
      env:
        GITHUB_REPO_TOKEN: ${{ inputs.repo-token }}
        INPUT_CONFIG_FILE: ${{ inputs.config-file }}
        INPUT_APPLY_FIXES: ${{ inputs.apply-fixes }}
