name: Check PR
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        if: github.event.action != 'edited'
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
      - name: Restore Cache
        if: github.event.action != 'edited'
        id: cache-build-logic-restore
        uses: actions/cache@v4
        with:
          path: build-logic/build/
          key: build-logic-${{ hashFiles('build-logic/**/*.gradle.kts', 'gradle/**') }}
      - run: ./gradlew check
        if: github.event.action != 'edited'
        shell: bash
      - name: Run Presubmit Checks
        uses: './'
        id: presubmitchecks
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/presubmitchecks.json
          # apply-fixes: "true"

#      - name: Commit Fixes
#        if: false && steps.presubmitchecks.outputs.applied-fixes == '1'
#        run: |
#          git config user.name "github-actions[bot]"
#          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
#          git add .
#          git commit -m "Presubmit Fixes"
#          git push
#        shell: bash
#      - uses: parkerbxyz/suggest-changes@v1
#        if: steps.presubmitchecks.outputs.applied-fixes == '1'
#        with:
#          comment: 'Please commit the suggested changes.'
#          event: 'COMMENT'
