name: Check PR
on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - run: ./gradlew assemble check
        shell: bash
      - name: Run Presubmit Checks
        uses: './'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}