name: Close PR
on:
  pull_request:
    types: [ closed ]

jobs:
  clear-caches:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Clear Actions Cache
        run: |
          gh cache list --ref "refs/pull/${{ github.event.pull_request.number }}/merge" --limit 100 --json key | jq -r '.[] | .key'
          gh cache list --ref "refs/pull/${{ github.event.pull_request.number }}/merge" --limit 100 --json key | jq -r '.[] | .key' | xargs -I {} gh cache delete "{}"
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
