name: Publish Release Artifacts

on:
  release:
    types: [prereleased, released, published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: write
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-${{github.event.release.tag_name}}
      cancel-in-progress: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Project Checks
        run: ./gradlew check
        shell: bash

      - name: Build Artifacts
        run: ./gradlew :presubmitchecks-cli:distZip :presubmitchecks-cli:fatJar

      - name: Generate Artifact Attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            presubmitchecks-cli/build/distributions/presubmitchecks-cli.zip
            presubmitchecks-cli/build/libs/presubmitchecks-cli-standalone.jar

      - name: Upload Artifacts to Release
        run: |
          echo Uploading Artifacts For ${{github.event.release.tag_name}}
          gh release upload ${{github.event.release.tag_name}} \
            presubmitchecks-cli/build/distributions/presubmitchecks-cli.zip \
            presubmitchecks-cli/build/libs/presubmitchecks-cli-standalone.jar \
            --clobber
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
